feat!: criteria per distance
tier4/driving_log_replayer pull request #339
Opened 2023-12-22 02:19 UTC by ktro2828

## Types of PR

- [x] New Features

## Description

Add support of testing with criteria in specified distance range(s).

## How to review this PR

- Requirements
  - Allow to test with criteria in specified distance range(s)
  - Allow to test without specifying filter parameters. 

## Others

2023-12-22 02:36 UTC, hayato-m126 requested changes
I'll just point out the obvious for now.

2023-12-22 02:36 UTC, hayato-m126 commented on driving_log_replayer/driving_log_replayer/perception.py
> +            method=self.condition.CriteriaMethod,
This change is no good because it undoes the changes made to the PR for adding the criteria in the MAPH.

https://github.com/tier4/driving_log_replayer/pull/337

2023-12-22 05:13 UTC, ktro2828 commented on driving_log_replayer/driving_log_replayer/perception.py
> +            method=self.condition.CriteriaMethod,
@hayato-m126 restored by https://github.com/tier4/driving_log_replayer/pull/339/commits/fe0991eb5de45d8e1e202dbc8f4974f1f0de1f6a

2024-01-10 09:23 UTC, hayato-m126 commented
Exit code is 1.

2024-01-11 06:02 UTC, hayato-m126 approved these changes
LGTM

2024-01-12 00:48 UTC, KeisukeShima approved these changes

2024-01-12 00:54 UTC, merged