feat: add perception object info to jsonl
tier4/driving_log_replayer pull request #452
Opened 2024-05-20 08:40 UTC by YoshiRi

## Types of PR

- [ ] New Features
- [x] Upgrade of existing features
- [ ] Bugfix

## Description

This PR is aiming to pass detailed perception result with lsim.
Currently, jsonl is used to store frame information and summary information.
After this PR, frame information contains detailed detected/ground truth object information.

## How to review this PR

I already asked web team to investigate affect

## Others

Some key of output dict may be changed after web consulting with web team.

2024-05-20 08:55 UTC, YoshiRi commented
Found unintended error, please wait for a while...

2024-05-20 16:04 UTC, hayato-m126 commented on driving_log_replayer/driving_log_replayer/perception_eval_conversions.py
> +    has_map_to_base_link = len(ego2map_matrix) > 0
ego2map is optional so none needs to be checked

```suggestion
    has_map_to_base_link = ego2map_matrix is not None and len(ego2map_matrix) > 0
```

2024-05-20 16:05 UTC, hayato-m126 requested changes
please check suggestion

2024-05-21 01:58 UTC, YoshiRi commented on driving_log_replayer/driving_log_replayer/perception_eval_conversions.py
> +    has_map_to_base_link = len(ego2map_matrix) > 0
Thank you. I fixed this in https://github.com/tier4/driving_log_replayer/pull/452/commits/bd6eb695301f9679443fe4568debd5a128cce8f2.

2024-05-21 01:59 UTC, YoshiRi commented
Please wait merge until discussion with tokunaga-san.

2024-05-21 10:40 UTC, YoshiRi commented
@hayato-m126 
Thanks for your review. According to discussion with @vios-fish, I add additional TODOs and reopen this PR after fix this.

- [ ] define json schema to clarify the new jsonl output
- [ ] fix code so that it use to json schema to create empty object
- [ ] update documentation about new output

2024-05-24 07:13 UTC, ktro2828 commented on driving_log_replayer/driving_log_replayer/perception_eval_conversions.py
> +    ego2map_matrix = pass_fail.ego2map
[NOTE] 
FYI in the latest `develop` branch in `perception_eval`, `PerceptionPassFailResult.ego2map` has been obsoleted and it is replaced by [`PerceptionPassFaileResult.transforms: <TransformDict>`](https://github.com/tier4/autoware_perception_evaluation/blob/e42931dbed6aa0d3632f29ca9c67eb0a176526f7/perception_eval/perception_eval/evaluation/result/perception_pass_fail_result.py#L67).

You can realize same behavior as follows:
```python
# from perception_eval.common.schema import FrameID
ego2map_matrix: HomogeneousMatrix | None = pass_fail.transforms.get((FrameID.BASE_LINK, FrameID.MAP))
# str key is also OK
# ego2map_matrix = pass_fail.transforms.get(("base_link", "map"))

...
gt_distance_bev = tp_gt.get_distance_bev(ego2map_matrix) if has_map_to_base_link else None
...
```

Reference of `TransformDict` and `HomogeneousMatrix`:
- https://github.com/tier4/autoware_perception_evaluation/blob/develop/perception_eval/perception_eval/common/transform.py

2024-06-27 23:43 UTC, ktro2828 commented on driving_log_replayer/driving_log_replayer/perception_eval_conversions.py
> +            has_map_to_base_link = ego2map_matrix.get((FrameID.BASE_LINK, FrameID.MAP)) is not None
The transformation feature has already been released in `perception_eval`! So, you can remove try-except block!

2024-06-28 07:20 UTC, hayato-m126 commented
```shell
perception_evaluator_node.py-62] Traceback (most recent call last):
[perception_evaluator_node.py-62]   File "/home/hyt/ros_ws/awf/install/driving_log_replayer/lib/driving_log_replayer/perception_evaluator_node.py", line 353, in <module>
[perception_evaluator_node.py-62]     main()
[perception_evaluator_node.py-62]   File "/home/hyt/ros_ws/awf/install/driving_log_replayer/local/lib/python3.10/dist-packages/driving_log_replayer/evaluator.py", line 377, in wrapper
[perception_evaluator_node.py-62]     executor.spin()
[perception_evaluator_node.py-62]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 294, in spin
[perception_evaluator_node.py-62]     self.spin_once()
[perception_evaluator_node.py-62]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 794, in spin_once
[perception_evaluator_node.py-62]     self._spin_once_impl(timeout_sec)
[perception_evaluator_node.py-62]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 791, in _spin_once_impl
[perception_evaluator_node.py-62]     future.result()
[perception_evaluator_node.py-62]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 94, in result
[perception_evaluator_node.py-62]     raise self.exception()
[perception_evaluator_node.py-62]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 239, in __call__
[perception_evaluator_node.py-62]     self._handler.send(None)
[perception_evaluator_node.py-62]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 437, in handler
[perception_evaluator_node.py-62]     await call_coroutine(entity, arg)
[perception_evaluator_node.py-62]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 362, in _execute_subscription
[perception_evaluator_node.py-62]     await await_or_execute(sub.callback, msg)
[perception_evaluator_node.py-62]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
[perception_evaluator_node.py-62]     return callback(*args)
[perception_evaluator_node.py-62]   File "/home/hyt/ros_ws/awf/install/driving_log_replayer/lib/driving_log_replayer/perception_evaluator_node.py", line 269, in perception_cb
[perception_evaluator_node.py-62]     marker_ground_truth, marker_results = self._result.set_frame(
[perception_evaluator_node.py-62]   File "/home/hyt/ros_ws/awf/install/driving_log_replayer/local/lib/python3.10/dist-packages/driving_log_replayer/perception.py", line 171, in set_frame
[perception_evaluator_node.py-62]     self._frame[criterion.name] = criterion.set_frame(frame)
[perception_evaluator_node.py-62]   File "/home/hyt/ros_ws/awf/install/driving_log_replayer/local/lib/python3.10/dist-packages/driving_log_replayer/perception.py", line 132, in set_frame
[perception_evaluator_node.py-62]     "Objects": FrameDescriptionWriter.extract_pass_fail_objects_description(
[perception_evaluator_node.py-62]   File "/home/hyt/ros_ws/awf/install/driving_log_replayer/local/lib/python3.10/dist-packages/driving_log_replayer/perception_eval_conversions.py", line 454, in extract_pass_fail_objects_description
[perception_evaluator_node.py-62]     assert FrameDescriptionWriter.is_object_structure_valid(est_tp_description), (
[perception_evaluator_node.py-62] AssertionError: EST TP object description is invalid in file: /home/hyt/ros_ws/awf/install/driving_log_replayer/local/lib/python3.10/dist-packages/driving_log_replayer/perception_eval_conversions.py
```

2024-06-30 09:09 UTC, ktro2828 commented on driving_log_replayer/driving_log_replayer/perception_eval_conversions.py
> +        quat = obj.state.orientation.q.tolist()
Note that, `pyquaternion.Quaterion` is the order of `[w, x, y, z]`

2024-06-30 16:12 UTC, YoshiRi commented on driving_log_replayer/driving_log_replayer/perception_eval_conversions.py
> +        quat = obj.state.orientation.q.tolist()
Thanks! Fixed in https://github.com/tier4/driving_log_replayer/pull/452/commits/b5b6c8732198dddcfdb2fc4fa4076dd2d57a39b2.

2024-07-01 10:39 UTC, YoshiRi commented on driving_log_replayer/driving_log_replayer/perception_eval_conversions.py
> +            has_map_to_base_link = ego2map_matrix.get((FrameID.BASE_LINK, FrameID.MAP)) is not None
I want to keep this try-except because the recent pilot-auto does not pulling latest DLR main and each projects may want this feature without supporting other. 
@ktro2828 How do you think about it?

2024-07-02 06:12 UTC, hayato-m126 approved these changes
LGTM

2024-07-12 02:08 UTC, vios-fish approved these changes

2024-07-12 15:19 UTC, merged