feat!: #498 apply t4 dataset for all evaluations
tier4/driving_log_replayer pull request #513
Opened 2024-07-08 17:09 UTC by hayato-m126

## Types of PR

- [x] New Features

## Description

Breaking Changes

- Changed to use t4_dataset for all evaluations
- change package name

## How to review this PR

I would like to have a review of the document update.
I have updated Quick Start and would like reviewers to try to follow the instructions.

```shell
git checkout feat/#498-apply-t4-dataset-for-all-evaluations
pip3 install mkdocs mkdocs-material mkdocs-awesome-pages-plugin mkdocs-static-i18n mdx-truly-sane-lists
mkdocs serve
# access http://localhost:8000 with your brower
```

## Others

2024-07-12 00:50 UTC, SakodaShintaro reviewed
I am still reviewing, but I made a few minor points.

2024-07-12 00:50 UTC, SakodaShintaro commented on docs/quick_start/setup.en.md
> +   source ~/autoware/install/setup
```suggestion
   source ~/autoware/install/setup.bash
```

or 

```
   source $AUTOWARE_PATH/install/setup.bash
```

2024-07-12 00:50 UTC, SakodaShintaro commented on docs/quick_start/run.en.md
> +```
NG(1)
```bash
shintarosakoda@dpc2304005:~/autoware$ ros2 launch log_evaluator log_evaluator.launch.py ~/log_evaluator/yabloc.yaml
malformed launch argument '/home/shintarosakoda/log_evaluator/yabloc.yaml', expected format '<name>:=<value>'
```

NG(2)
```bash
shintarosakoda@dpc2304005:~/autoware$ ros2 launch log_evaluator log_evaluator.launch.py scenario_path:=~/log_evaluator/yabloc.yaml
[INFO] [launch]: All log files can be found below /home/shintarosakoda/.ros/log/2024-07-12-09-33-46-134676-dpc2304005-185446
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): [Errno 2] No such file or directory: '~/log_evaluator/yabloc.yaml'
```

OK
```bash
shintarosakoda@dpc2304005:~/autoware$ ros2 launch log_evaluator log_evaluator.launch.py scenario_path:=$HOME/log_evaluator/yabloc.yaml
```

2024-07-12 00:50 UTC, SakodaShintaro commented on log_evaluator_migration_tool/README.md
> +python3 log_evaluator_migration_tool ${driving_log_replayer_data_directory_root}
```suggestion
python3 log_evaluator_migration_tool.py ${driving_log_replayer_data_directory_root}
```

2024-07-12 08:28 UTC, SakodaShintaro requested changes
I used the migration tool to convert the data and scenario yaml files, and confirmed that the log_evaluator works properly. :+1: 
I think this is a good improvement.

If you fix the points I have raised, I will approve this PR.

2024-07-12 08:28 UTC, SakodaShintaro commented on docs/scenario_format/index.ja.md
> +複数個のDatasetを記述した場合は、利用したいdatasetのindexをlaunchの起動引数に渡す必要がある。渡さない場合は0番が暗黙で使われる。
When using a scenario where multiple datasets are described, I think it may be better to raise an error if the "index" argument is not passed.

2024-07-12 08:45 UTC, hayato-m126 commented on docs/quick_start/run.en.md
> +```
I fixed it with the following commit hash.
42328d2469b4a7c11baf5c77e590b099313e334e

2024-07-12 10:18 UTC, hayato-m126 commented on docs/scenario_format/index.ja.md
> +複数個のDatasetを記述した場合は、利用したいdatasetのindexをlaunchの起動引数に渡す必要がある。渡さない場合は0番が暗黙で使われる。
I fixed this point with the following commit hash.
3fc90eb0e69e7f21fb23595818daabf6dd7cab2e

2024-07-16 00:53 UTC, SakodaShintaro approved these changes
Thank you for addressing my comments.
Looks Good To Me

2024-07-16 04:10 UTC, merged