feat: add covariance information in jsonl
tier4/driving_log_replayer pull request #568
Opened 2024-10-01 02:44 UTC by YoshiRi

## Types of PR

- [x] New Features
- [ ] Upgrade of existing features
- [ ] Bugfix

## Description

Author wants to add covariance information into jsonl. This will help to evaluate centerpoint_sigma model. See https://tier4.atlassian.net/browse/RT1-8002 for TIER IV members.

This PR must merged after https://github.com/tier4/autoware_perception_evaluation/pull/190.

## How to review this PR
Run evaluator and see the result.

## Others

2024-10-01 02:53 UTC, YoshiRi commented
Running Evaluator now https://evaluation.tier4.jp/evaluation/reports/790172a6-29fd-5ec5-954b-b1565bb6533e?project_id=prd_jt

2024-10-01 15:30 UTC, YoshiRi commented
Rerun test: https://evaluation.tier4.jp/evaluation/reports/e29ca7f4-a94a-5f7d-a328-e3cee7ea4197?project_id=prd_jt

2024-10-01 16:39 UTC, ktro2828 approved these changes

2024-10-02 07:31 UTC, hayato-m126 requested changes
please fix  unit test

2024-10-02 10:42 UTC, ktro2828 commented
@YoshiRi @hayato-m126 After releasing perception eval, unit testing succeeded

2024-10-02 10:52 UTC, merged